name: Secret Key Malaysia
favicon: null
layout_spectrum: 0.3918923845048994
typography_spectrum: 0.9934261192101985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5328236627392471
  lightness: 0.047756762243807316
  saturation: 0.9844662032555789
  rhythmicContrast: 0.6699634806718677
purpose: []
